apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
