# Default values for hello-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.gitlab.com/akilan468/go-gitlab-argocd
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  imagePullPolicy: Always
container:
  name: go-gitlab-argocd
  port: 3000
  replicas: 4
service:
  type: NodePort
